networks:
  hackathon_network:
    driver: bridge

x-employee-service:
  &employee-service
  build:
    context: .
    dockerfile: EmployeeService/Dockerfile
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
  volumes:
    - ./EmployeeService/Resources:/app/Resources
  image: employee:latest
  deploy:
    replicas: 1
  networks:
    - hackathon_network
  depends_on:
    rabbitmq:
      condition: service_healthy

services:
  hackathon_database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.containers/hackathon-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
    networks:
      - hackathon_network

  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: rmuser
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    volumes:
      - ./.containers/rabbitmq/data:/var/lib/rabbitmq
      - ./.containers/rabbitmq/logs:/var/log/rabbitmq
    networks:
      - hackathon_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  hr-director:
    build:
      context: .
      dockerfile: HrDirector/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: hr-director:latest
    deploy:
      replicas: 1
    ports:
      - "${HR_DIRECTOR_PORT}:${HR_DIRECTOR_INTERNAL_PORT}"
    networks:
      - hackathon_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      hackathon_database:
        condition: service_healthy
  
  hr-manager:
    build:
      context: .
      dockerfile: HrManager/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HR_DIRECTOR_URL=http://hr-director:${HR_DIRECTOR_INTERNAL_PORT}/api/harmony
    volumes:
      - ./HrManager/Resources:/app/Resources
    image: hr-manager:latest
    deploy:
      replicas: 1
    ports:
      - "${HR_MANAGER_PORT}:${HR_MANAGER_INTERNAL_PORT}"
    networks:
      - hackathon_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  junior-1:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=junior
      - EMPLOYEE_ID=1
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${JUNIOR_1_PORT}:${JUNIOR_1_INTERNAL_PORT}"

  junior-2:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=junior
      - EMPLOYEE_ID=2
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${JUNIOR_2_PORT}:${JUNIOR_2_INTERNAL_PORT}"

  junior-3:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=junior
      - EMPLOYEE_ID=3
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${JUNIOR_3_PORT}:${JUNIOR_3_INTERNAL_PORT}"

  junior-4:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=junior
      - EMPLOYEE_ID=4
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${JUNIOR_4_PORT}:${JUNIOR_4_INTERNAL_PORT}"

  junior-5:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=junior
      - EMPLOYEE_ID=5
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${JUNIOR_5_PORT}:${JUNIOR_5_INTERNAL_PORT}"
  
  
  teamlead-1:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=teamLead
      - EMPLOYEE_ID=6
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${TEAMLEAD_1_PORT}:${TEAMLEAD_1_INTERNAL_PORT}"

  teamlead-2:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=teamLead
      - EMPLOYEE_ID=7
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${TEAMLEAD_2_PORT}:${TEAMLEAD_2_INTERNAL_PORT}"

  teamlead-3:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=teamLead
      - EMPLOYEE_ID=8
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${TEAMLEAD_3_PORT}:${TEAMLEAD_3_INTERNAL_PORT}"

  teamlead-4:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=teamLead
      - EMPLOYEE_ID=9
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${TEAMLEAD_4_PORT}:${TEAMLEAD_4_INTERNAL_PORT}"

  teamlead-5:
    <<: *employee-service
    environment:
      - EMPLOYEE_TYPE=teamLead
      - EMPLOYEE_ID=10
      - HR_MANAGER_URL=http://hr-manager:${HR_MANAGER_INTERNAL_PORT}/api/teams/{EMPLOYEE_TYPE}-wishlist
    ports:
      - "${TEAMLEAD_5_PORT}:${TEAMLEAD_5_INTERNAL_PORT}"
